spring.datasource.url=jdbc:mysql://localhost:3306/checkpoint?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true